spring.application.name=project-crud-operation

spring.datasource.url=jdbc:postgresql://localhost:5432/Books
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.security.user.name = smriti
#spring.security.user.password= smiti



server.port=9090